#pragma once

#define CAN_SWERVE_REAR_LEFT_TURN 8
#define CAN_SWERVE_REAR_LEFT_MOVE 4 //3

#define CAN_SWERVE_REAR_RIGHT_TURN 7
#define CAN_SWERVE_REAR_RIGHT_MOVE 3 //3

#define CAN_SWERVE_FRONT_LEFT_TURN 6
#define CAN_SWERVE_FRONT_LEFT_MOVE 2 //3

#define CAN_SWERVE_FRONT_RIGHT_TURN 5
#define CAN_SWERVE_FRONT_RIGHT_MOVE 1 //3
